import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./layout/Navbar";
import Footer from "./layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Keith Brown",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="business" lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
